/**
 * Generated by `scripts/build-skills.mjs` from `skills/<name>/SKILL.md` — do not edit.
 *
 * Edit the SKILL.md bundles and run `pnpm build` (or `node scripts/build-skills.mjs`).
 * `pnpm verify` fails when this file and those bundles have drifted apart.
 */
import type { YonBundledSkill } from './skill-catalog.ts';
/** Every skill this plugin ships, in name order. */
export declare const YON_BUNDLED_SKILLS: readonly YonBundledSkill[];
