/**
 * Generated by `scripts/build-skills.mjs` from `skills/<name>/SKILL.md` — do not edit.
 *
 * Edit the SKILL.md bundles and run `pnpm build` (or `node scripts/build-skills.mjs`).
 * `pnpm verify` fails when this file and those bundles have drifted apart.
 */

import type { YonBundledSkill } from './skill-catalog.ts'

/** Every skill this plugin ships, in name order. */
export const YON_BUNDLED_SKILLS: readonly YonBundledSkill[] = [
  {
    name: 'yon-db-query',
    description: '查用友客开环境的数据。先用 datasource_list 看插件里登记了哪些库，再用 datasource_query 执行 SQL；连接信息、驱动与密码都由插件宿主处理，不需要你去拼连接串或找脚本。',
    whenToUse: '使用者要求查某个项目/环境的数据、验证一条 SQL、核对表结构或数据是否符合预期时。',
    content: `# 查用友环境的数据

> 这个技能由 \`dsh-plugin-yon-panel\` 插件预制：安装插件时它自动进入技能目录，卸载时自动消失。
> 查询脚本、驱动适配都在插件包里，**不依赖 \`~/.claude\`、\`~/.agents\` 或任何外部技能目录**。

## 两个工具，不要绕开

| 工具 | 用途 |
|---|---|
| \`datasource_list\` | 看有哪些数据源：项目、环境、类型、地址、可用登录名 |
| \`datasource_query\` | 对指定数据源执行一条 SQL |

**不要**自己去找 \`db_query.py\`、也不要拼 \`python ... -p xxx -e test\` 这类命令：插件的安装路径每台机器都不同，
而工具已经把连接解析、驱动选择、超时和结果格式化都做完了。

**不要**凭记忆写连接串。连接信息存在插件管理的数据源配置里，\`datasource_list\` 是唯一可信的来源。

## 推荐顺序

1. \`datasource_list\` —— 看清有哪些环境、各自的 \`key\`、类型和登录名；
2. 用**完整 key**（形如 \`天九(NCC2312)::test\`）调 \`datasource_query\`，不要用简称：键是精确标识，简称可能匹配到别的项目；
3. 拿不准表名或字段名时，先查元数据表（例如 Oracle 的 \`user_tab_columns\`）再写正式 SQL。

## SQL 写法要点

- 限定数据库方言：Oracle 用 \`SELECT 1 FROM DUAL\`，MySQL / 达梦 / PostgreSQL 用 \`SELECT 1\`；
- 一次只发一条语句，工具返回的是结果集，不做多语句编排；
- 大结果集会占用上下文：先 \`COUNT(*)\` 或加 \`WHERE\`/\`ROWNUM\`/\`LIMIT\` 收敛，再取明细。

## 写操作会被拦下来

\`datasource_query\` 遇到 \`INSERT\`、\`UPDATE\`、\`DELETE\`、\`DROP\`、\`TRUNCATE\`、\`ALTER\`、\`CREATE\`
这类语句会先停下来等使用者确认，并且**生产环境**的写操作一律要明确批准。这不是可以绕过的提示：

- 不要为了"先试试"而对生产库发写语句；
- 使用者没有明确要求时，默认只发 \`SELECT\`；
- 被拒绝就把原因原样告诉使用者，不要换一条等价写法重试。

## 边界

- 本技能只负责**查询**。连接的新增、修改、删除在使用者的面板里做（侧边栏底部的 \`Y\` → 数据库图标），
  因为那里才需要输入密码，而密码不会进到你的上下文里。
- 数据源里没有你要连的库时，告诉使用者去哪加，不要自己去改配置文件。
`,
  },
  {
    name: 'yon-devkit',
    description: '用友客开项目的配置入口。先用 Yon 面板登记的项目信息读取环境地址、账号、部署路径、版本号，再去查代码或连环境，避免重复询问使用者。',
    whenToUse: '使用者提到某个用友客开项目（NCC/BIP）的环境、地址、账号、部署路径、版本号，或说"接着上次那个项目继续"时。',
    content: `# Yon 用友客开工作台

> 这个技能由 \`dsh-plugin-yon-panel\` 插件预制：安装插件时它自动进入技能目录，卸载插件时自动消失。
> 它不写进 \`~/.agents/skills\`，也不和通用技能混在一起。
>
> **当前是占位内容**，用来验证"插件预制技能"的完整链路；真实的用友客开约定由插件维护者补充。

## 先查配置，再问人

用友客开的环境信息通常散落在聊天记录、配置文件、部署脚本里。这个插件把它们收成"项目 + 任意字段"：

- 面板：侧边栏底部的 \`Y\` → 文件夹图标 → 项目管理
- 模型工具：\`project_list\`、\`project_read\`、\`project_create\`、\`project_update\`、\`project_delete\`

推荐顺序：

1. \`project_list\` 看已登记的项目；
2. \`project_read\` 读目标项目的全部字段（环境地址、账号、部署路径、版本号……）；
3. 只有字段里确实没有的信息，才去问使用者或连环境确认。

改动配置走 \`project_update\`：它会先给出改动前后的对比，由使用者确认后才写入。

## 该往项目里登记什么

字段名和值都由使用者定义；值能按 JSON 解析就存 JSON，否则存文本。用友客开常见字段：

| 字段名 | 说明 |
|---|---|
| \`环境地址\` | 应用服务器地址 |
| \`数据库\` | 数据库连接串 |
| \`部署路径\` | 补丁或资产包的投放目录 |
| \`版本\` | 产品版本，例如 NCC 2111、BIP 旗舰版 |
| \`备注\` | 该项目特有的坑 |

## 边界

- 本技能只负责**读取已登记的配置**，不包含任何数据库或服务器凭据。
- 具体的产品开发规范不在这里：NCC 客开查 \`yon-ncc-dev\`，BIP 旗舰版查 \`yonyou-bip-dev\`，两者与本技能是"规范"与"项目配置"的分工，不要互相替代。
`,
  },
  {
    name: 'yon-wiki',
    description: '查用友知识库里的实体、物理表与字段。写 SQL 或写代码要落到具体表名/列名之前，先用 wiki_lookup 找到实体页，再用 wiki_read 读它的字段清单；不要凭记忆编造表名或列名。',
    whenToUse: '需要确认某个用友单据/实体/业务对象对应的物理表名、数据库列名、domain/schema，或看到报错里的表名、代码里的实体 URI 想弄清它是什么时。',
    content: `# 查用友知识库

> 这个技能由 \`dsh-plugin-yon-panel\` 插件预制：安装插件时它自动进入技能目录，卸载时自动消失。
> 知识库位于使用者自己的 Obsidian vault 里（通常是 \`D:\\yon-bip-obsidian\\\` 下的 BIP / NCC 两套），
> 路径由插件管理，**不需要你去翻目录或拼文件路径**。

## 什么时候必须用它

**写 SQL 之前、写涉及表名或字段名的代码之前。** 用友实体到数据库表的对应关系不适合靠记忆：

- 同一业务概念在不同产品线（BIP 旗舰版 / NCC）底层表完全不同；
- 引用型字段的 \`name\`（Java 驼峰名）和 \`fieldName\`（数据库列名）经常不一致；
- 字段编码、枚举取值这类细节，猜错不会报错，只会静默查出错数据。

## 两个工具，不要绕开

| 工具 | 用途 |
|---|---|
| \`wiki_lookup\` | 用一个名字找页面：实体 URI、物理表名、中文显示名、或它们的一段片段 |
| \`wiki_read\` | 读某个页面的全文，含字段清单（字段编码 ↔ 数据库列） |

**不要**去 grep vault 目录、也不要凭记忆拼 \`wiki/entities/xxx.md\` 路径：索引已经建好，
\`wiki_lookup\` 是毫秒级的，而全文检索几千个文件既慢又容易漏。

## 推荐顺序

1. 手上有什么就用什么去 \`wiki_lookup\`：代码里是 \`voucher.order.Order\` 就查 URI，报错里是
   \`ucg_baseapi_api_info\` 就查表名，需求里是"销售订单"就查中文名；
2. 看返回的**匹配方式**：\`URI 精确\` / \`物理表精确\` / \`页面名精确\` 是可靠命中，
   \`包含\` 只是片段相符，必须再核对一眼；
3. \`wiki_read\` 读中意的那页，拿 \`物理表\`、\`domain/服务域\` 和字段清单；
4. 再写 SQL。写之前**顺手核对一次**：关键的表名/列名用 \`datasource_query\` 发一条
   \`SELECT ... WHERE 1=0\` 验证存在性，比事后排查便宜得多。

## 可信度要自己判断

每个页面都带两个字段，**返回结果里一定会给**，请据此决定信几分：

| 字段 | 含义 |
|---|---|
| \`version\` | 知识适用的平台版本（BIP V5 / BIP R6 / NCC 2111 / NCC 2505…）。**版本不符就不要直接用。** |
| \`status\` / \`verified\` | \`verified\` 是已在真实环境验证过；\`unverified\` 是从文档提取、尚未验证；\`outdated\` 已过期 |

\`unverified\` 的页面**可以当线索，不能当结论**——用它定位，再用 \`datasource_query\` 确认。
两个页面说法矛盾时，先看 \`version\`：**不同版本的不同行为不算矛盾**；同版本矛盾才需要向使用者指出。

## 边界

- 这两个工具**只读**。往知识库里写页面（消化新实体）是另一件事，目前不通过本技能做；
- 知识库里没有的实体，如实告诉使用者"知识库未收录"，**不要用记忆里的表名充数**；
- 知识库路径是使用者的本机配置。查不到任何东西时，先确认 Yon 面板「知识库」里登记了 vault，
  而不是反复换关键词猜。
`,
  },
]
